version: '3'
services:
  uio:
    image: mariadb:latest
    container_name: mariadbc
    ports:
      - "2004:3306"
    networks:
      - network04
    volumes:
      - led:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myrootw
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=myhost


networks:
  network04:
    driver: bridge
volumes:
  led:
